/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const AnalysisResult = IDL.Record({
  'region' : IDL.Text,
  'status' : IDL.Text,
  'probability' : IDL.Float64,
  'ashOk' : IDL.Bool,
  'supplier' : IDL.Text,
  'extractiveOk' : IDL.Bool,
  'anomalyDetails' : IDL.Text,
  'qualityScore' : IDL.Float64,
  'moistureOk' : IDL.Bool,
  'heavyMetalsOk' : IDL.Bool,
  'dateReceived' : IDL.Text,
  'timestamp' : IDL.Int,
  'microbialOk' : IDL.Bool,
  'batchId' : IDL.Text,
  'herbName' : IDL.Text,
  'anomaly' : IDL.Bool,
});
export const BatchInput = IDL.Record({
  'ash' : IDL.Float64,
  'region' : IDL.Text,
  'supplier' : IDL.Text,
  'heavyMetals' : IDL.Float64,
  'extractiveValue' : IDL.Float64,
  'dateReceived' : IDL.Text,
  'notes' : IDL.Text,
  'microbialCount' : IDL.Float64,
  'batchId' : IDL.Text,
  'herbName' : IDL.Text,
  'moisture' : IDL.Float64,
});
export const UserRecord = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'institution' : IDL.Text,
  'approvedAt' : IDL.Opt(IDL.Int),
  'name' : IDL.Text,
  'accessCode' : IDL.Opt(IDL.Text),
  'codeGeneratedAt' : IDL.Opt(IDL.Int),
  'email' : IDL.Text,
  'registeredAt' : IDL.Int,
  'purpose' : IDL.Text,
});
export const Batch = IDL.Record({
  'id' : IDL.Nat,
  'ash' : IDL.Float64,
  'region' : IDL.Text,
  'supplier' : IDL.Text,
  'createdBy' : IDL.Principal,
  'heavyMetals' : IDL.Float64,
  'extractiveValue' : IDL.Float64,
  'dateReceived' : IDL.Text,
  'notes' : IDL.Text,
  'microbialCount' : IDL.Float64,
  'batchId' : IDL.Text,
  'herbName' : IDL.Text,
  'moisture' : IDL.Float64,
});
export const DashboardStats = IDL.Record({
  'passRate' : IDL.Float64,
  'totalBatches' : IDL.Nat,
  'passCount' : IDL.Nat,
  'avgQualityScore' : IDL.Float64,
  'openDeviations' : IDL.Nat,
  'failCount' : IDL.Nat,
});
export const AppRole = IDL.Variant({
  'admin' : IDL.Null,
  'qaManager' : IDL.Null,
  'labTechnician' : IDL.Null,
});
export const QualityOverview = IDL.Record({
  'avgScore' : IDL.Float64,
  'total' : IDL.Nat,
  'highRisk' : IDL.Nat,
  'failed' : IDL.Nat,
  'passed' : IDL.Nat,
});
export const RiskBatch = IDL.Record({
  'supplier' : IDL.Text,
  'qualityScore' : IDL.Float64,
  'batchId' : IDL.Text,
  'herbName' : IDL.Text,
  'riskLevel' : IDL.Text,
});
export const RiskAuditEntry = IDL.Record({
  'userName' : IDL.Text,
  'userId' : IDL.Text,
  'timestamp' : IDL.Int,
  'riskLevel' : IDL.Text,
  'creditsUsed' : IDL.Nat,
  'riskScore' : IDL.Nat,
  'systemName' : IDL.Text,
});
export const ScoreTrend = IDL.Record({
  'qualityScore' : IDL.Float64,
  'timestamp' : IDL.Int,
  'batchId' : IDL.Text,
});
export const SupplierStats = IDL.Record({
  'avgScore' : IDL.Float64,
  'passRate' : IDL.Float64,
  'supplier' : IDL.Text,
  'totalBatches' : IDL.Nat,
});
export const AyurNexis = IDL.Service({
  '_transform' : IDL.Func(
      [
        IDL.Record({
          'context' : IDL.Vec(IDL.Nat8),
          'response' : http_request_result,
        }),
      ],
      [http_request_result],
      ['query'],
    ),
  'addAdmin' : IDL.Func([IDL.Principal], [], []),
  'adminApproveUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'adminDeleteUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'adminGenerateCode' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Opt(IDL.Text)],
      [],
    ),
  'adminRevokeUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'analyzeBatch' : IDL.Func([IDL.Nat], [IDL.Opt(AnalysisResult)], []),
  'callDeepSeek' : IDL.Func([IDL.Text], [IDL.Text], []),
  'callDeepSeekExtended' : IDL.Func([IDL.Text], [IDL.Text], []),
  'checkUserAccess' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'createBatch' : IDL.Func([BatchInput], [IDL.Nat], []),
  'deductCredit' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteBatch' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAccessRequests' : IDL.Func([IDL.Text], [IDL.Vec(UserRecord)], ['query']),
  'getAllAnalyses' : IDL.Func([], [IDL.Vec(AnalysisResult)], ['query']),
  'getAllBatches' : IDL.Func([], [IDL.Vec(Batch)], ['query']),
  'getAllUserCredits' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getAnalysis' : IDL.Func([IDL.Text], [IDL.Opt(AnalysisResult)], ['query']),
  'getBatch' : IDL.Func([IDL.Nat], [IDL.Opt(Batch)], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getDeviationReport' : IDL.Func([], [IDL.Vec(AnalysisResult)], ['query']),
  'getMyAppRole' : IDL.Func([], [IDL.Opt(AppRole)], ['query']),
  'getQualityOverview' : IDL.Func([], [QualityOverview], ['query']),
  'getRiskAssessment' : IDL.Func([], [IDL.Vec(RiskBatch)], ['query']),
  'getRiskAuditLog' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(RiskAuditEntry)],
      ['query'],
    ),
  'getScoreTrends' : IDL.Func([], [IDL.Vec(ScoreTrend)], ['query']),
  'getSupplierStats' : IDL.Func([], [IDL.Vec(SupplierStats)], ['query']),
  'getUserCodeExpiry' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Tuple(IDL.Int, IDL.Nat))],
      ['query'],
    ),
  'getUserCredits' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], ['query']),
  'getUserOwnCredits' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getUserRecord' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(UserRecord)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logRiskPrediction' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'removeAdmin' : IDL.Func([IDL.Principal], [], []),
  'seedDemoData' : IDL.Func([], [], []),
  'setAppRole' : IDL.Func([IDL.Principal, AppRole], [], []),
  'setUserCredits' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Bool], []),
  'submitAccessRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
      [IDL.Bool],
      [],
    ),
  'updateBatch' : IDL.Func([IDL.Nat, BatchInput], [IDL.Bool], []),
  'verifyUserCode' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
});

export const idlService = AyurNexis;

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const AnalysisResult = IDL.Record({
    'region' : IDL.Text,
    'status' : IDL.Text,
    'probability' : IDL.Float64,
    'ashOk' : IDL.Bool,
    'supplier' : IDL.Text,
    'extractiveOk' : IDL.Bool,
    'anomalyDetails' : IDL.Text,
    'qualityScore' : IDL.Float64,
    'moistureOk' : IDL.Bool,
    'heavyMetalsOk' : IDL.Bool,
    'dateReceived' : IDL.Text,
    'timestamp' : IDL.Int,
    'microbialOk' : IDL.Bool,
    'batchId' : IDL.Text,
    'herbName' : IDL.Text,
    'anomaly' : IDL.Bool,
  });
  const BatchInput = IDL.Record({
    'ash' : IDL.Float64,
    'region' : IDL.Text,
    'supplier' : IDL.Text,
    'heavyMetals' : IDL.Float64,
    'extractiveValue' : IDL.Float64,
    'dateReceived' : IDL.Text,
    'notes' : IDL.Text,
    'microbialCount' : IDL.Float64,
    'batchId' : IDL.Text,
    'herbName' : IDL.Text,
    'moisture' : IDL.Float64,
  });
  const UserRecord = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'institution' : IDL.Text,
    'approvedAt' : IDL.Opt(IDL.Int),
    'name' : IDL.Text,
    'accessCode' : IDL.Opt(IDL.Text),
    'codeGeneratedAt' : IDL.Opt(IDL.Int),
    'email' : IDL.Text,
    'registeredAt' : IDL.Int,
    'purpose' : IDL.Text,
  });
  const Batch = IDL.Record({
    'id' : IDL.Nat,
    'ash' : IDL.Float64,
    'region' : IDL.Text,
    'supplier' : IDL.Text,
    'createdBy' : IDL.Principal,
    'heavyMetals' : IDL.Float64,
    'extractiveValue' : IDL.Float64,
    'dateReceived' : IDL.Text,
    'notes' : IDL.Text,
    'microbialCount' : IDL.Float64,
    'batchId' : IDL.Text,
    'herbName' : IDL.Text,
    'moisture' : IDL.Float64,
  });
  const DashboardStats = IDL.Record({
    'passRate' : IDL.Float64,
    'totalBatches' : IDL.Nat,
    'passCount' : IDL.Nat,
    'avgQualityScore' : IDL.Float64,
    'openDeviations' : IDL.Nat,
    'failCount' : IDL.Nat,
  });
  const AppRole = IDL.Variant({
    'admin' : IDL.Null,
    'qaManager' : IDL.Null,
    'labTechnician' : IDL.Null,
  });
  const QualityOverview = IDL.Record({
    'avgScore' : IDL.Float64,
    'total' : IDL.Nat,
    'highRisk' : IDL.Nat,
    'failed' : IDL.Nat,
    'passed' : IDL.Nat,
  });
  const RiskBatch = IDL.Record({
    'supplier' : IDL.Text,
    'qualityScore' : IDL.Float64,
    'batchId' : IDL.Text,
    'herbName' : IDL.Text,
    'riskLevel' : IDL.Text,
  });
  const RiskAuditEntry = IDL.Record({
    'userName' : IDL.Text,
    'userId' : IDL.Text,
    'timestamp' : IDL.Int,
    'riskLevel' : IDL.Text,
    'creditsUsed' : IDL.Nat,
    'riskScore' : IDL.Nat,
    'systemName' : IDL.Text,
  });
  const ScoreTrend = IDL.Record({
    'qualityScore' : IDL.Float64,
    'timestamp' : IDL.Int,
    'batchId' : IDL.Text,
  });
  const SupplierStats = IDL.Record({
    'avgScore' : IDL.Float64,
    'passRate' : IDL.Float64,
    'supplier' : IDL.Text,
    'totalBatches' : IDL.Nat,
  });
  const AyurNexis = IDL.Service({
    '_transform' : IDL.Func(
        [
          IDL.Record({
            'context' : IDL.Vec(IDL.Nat8),
            'response' : http_request_result,
          }),
        ],
        [http_request_result],
        ['query'],
      ),
    'addAdmin' : IDL.Func([IDL.Principal], [], []),
    'adminApproveUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'adminDeleteUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'adminGenerateCode' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Opt(IDL.Text)],
        [],
      ),
    'adminRevokeUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'analyzeBatch' : IDL.Func([IDL.Nat], [IDL.Opt(AnalysisResult)], []),
    'callDeepSeek' : IDL.Func([IDL.Text], [IDL.Text], []),
    'callDeepSeekExtended' : IDL.Func([IDL.Text], [IDL.Text], []),
    'checkUserAccess' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'createBatch' : IDL.Func([BatchInput], [IDL.Nat], []),
    'deductCredit' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteBatch' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAccessRequests' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(UserRecord)],
        ['query'],
      ),
    'getAllAnalyses' : IDL.Func([], [IDL.Vec(AnalysisResult)], ['query']),
    'getAllBatches' : IDL.Func([], [IDL.Vec(Batch)], ['query']),
    'getAllUserCredits' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getAnalysis' : IDL.Func([IDL.Text], [IDL.Opt(AnalysisResult)], ['query']),
    'getBatch' : IDL.Func([IDL.Nat], [IDL.Opt(Batch)], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getDeviationReport' : IDL.Func([], [IDL.Vec(AnalysisResult)], ['query']),
    'getMyAppRole' : IDL.Func([], [IDL.Opt(AppRole)], ['query']),
    'getQualityOverview' : IDL.Func([], [QualityOverview], ['query']),
    'getRiskAssessment' : IDL.Func([], [IDL.Vec(RiskBatch)], ['query']),
    'getRiskAuditLog' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(RiskAuditEntry)],
        ['query'],
      ),
    'getScoreTrends' : IDL.Func([], [IDL.Vec(ScoreTrend)], ['query']),
    'getSupplierStats' : IDL.Func([], [IDL.Vec(SupplierStats)], ['query']),
    'getUserCodeExpiry' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Tuple(IDL.Int, IDL.Nat))],
        ['query'],
      ),
    'getUserCredits' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], ['query']),
    'getUserOwnCredits' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getUserRecord' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(UserRecord)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logRiskPrediction' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'removeAdmin' : IDL.Func([IDL.Principal], [], []),
    'seedDemoData' : IDL.Func([], [], []),
    'setAppRole' : IDL.Func([IDL.Principal, AppRole], [], []),
    'setUserCredits' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Bool], []),
    'submitAccessRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
        [IDL.Bool],
        [],
      ),
    'updateBatch' : IDL.Func([IDL.Nat, BatchInput], [IDL.Bool], []),
    'verifyUserCode' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
  });
  
  return AyurNexis;
};

export const init = ({ IDL }) => { return []; };