/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalysisResult {
  'region' : string,
  'status' : string,
  'probability' : number,
  'ashOk' : boolean,
  'supplier' : string,
  'extractiveOk' : boolean,
  'anomalyDetails' : string,
  'qualityScore' : number,
  'moistureOk' : boolean,
  'heavyMetalsOk' : boolean,
  'dateReceived' : string,
  'timestamp' : bigint,
  'microbialOk' : boolean,
  'batchId' : string,
  'herbName' : string,
  'anomaly' : boolean,
}
export type AppRole = { 'admin' : null } |
  { 'qaManager' : null } |
  { 'labTechnician' : null };
export interface AyurNexis {
  '_transform' : ActorMethod<
    [{ 'context' : Uint8Array, 'response' : http_request_result }],
    http_request_result
  >,
  'addAdmin' : ActorMethod<[Principal], undefined>,
  'adminApproveUser' : ActorMethod<[string, string], boolean>,
  'adminDeleteUser' : ActorMethod<[string, string], boolean>,
  'adminGenerateCode' : ActorMethod<[string, string, bigint], [] | [string]>,
  'adminRevokeUser' : ActorMethod<[string, string], boolean>,
  'analyzeBatch' : ActorMethod<[bigint], [] | [AnalysisResult]>,
  'callDeepSeek' : ActorMethod<[string], string>,
  'callDeepSeekExtended' : ActorMethod<[string], string>,
  'checkUserAccess' : ActorMethod<[string], string>,
  'createBatch' : ActorMethod<[BatchInput], bigint>,
  'deductCredit' : ActorMethod<[string], boolean>,
  'deleteBatch' : ActorMethod<[bigint], boolean>,
  'getAccessRequests' : ActorMethod<[string], Array<UserRecord>>,
  'getAllAnalyses' : ActorMethod<[], Array<AnalysisResult>>,
  'getAllBatches' : ActorMethod<[], Array<Batch>>,
  'getAllUserCredits' : ActorMethod<[string], Array<[string, bigint]>>,
  'getAnalysis' : ActorMethod<[string], [] | [AnalysisResult]>,
  'getBatch' : ActorMethod<[bigint], [] | [Batch]>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getDeviationReport' : ActorMethod<[], Array<AnalysisResult>>,
  'getMyAppRole' : ActorMethod<[], [] | [AppRole]>,
  'getQualityOverview' : ActorMethod<[], QualityOverview>,
  'getRiskAssessment' : ActorMethod<[], Array<RiskBatch>>,
  'getRiskAuditLog' : ActorMethod<[string], Array<RiskAuditEntry>>,
  'getScoreTrends' : ActorMethod<[], Array<ScoreTrend>>,
  'getSupplierStats' : ActorMethod<[], Array<SupplierStats>>,
  'getUserCodeExpiry' : ActorMethod<[string], [] | [[bigint, bigint]]>,
  'getUserCredits' : ActorMethod<[string, string], bigint>,
  'getUserOwnCredits' : ActorMethod<[string], bigint>,
  'getUserRecord' : ActorMethod<[string, string], [] | [UserRecord]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logRiskPrediction' : ActorMethod<
    [string, string, string, bigint, string],
    undefined
  >,
  'removeAdmin' : ActorMethod<[Principal], undefined>,
  'seedDemoData' : ActorMethod<[], undefined>,
  'setAppRole' : ActorMethod<[Principal, AppRole], undefined>,
  'setUserCredits' : ActorMethod<[string, bigint, string], boolean>,
  'submitAccessRequest' : ActorMethod<
    [string, string, string, string, string, bigint],
    boolean
  >,
  'updateBatch' : ActorMethod<[bigint, BatchInput], boolean>,
  'verifyUserCode' : ActorMethod<[string, string], [] | [string]>,
}
export interface Batch {
  'id' : bigint,
  'ash' : number,
  'region' : string,
  'supplier' : string,
  'createdBy' : Principal,
  'heavyMetals' : number,
  'extractiveValue' : number,
  'dateReceived' : string,
  'notes' : string,
  'microbialCount' : number,
  'batchId' : string,
  'herbName' : string,
  'moisture' : number,
}
export interface BatchInput {
  'ash' : number,
  'region' : string,
  'supplier' : string,
  'heavyMetals' : number,
  'extractiveValue' : number,
  'dateReceived' : string,
  'notes' : string,
  'microbialCount' : number,
  'batchId' : string,
  'herbName' : string,
  'moisture' : number,
}
export interface DashboardStats {
  'passRate' : number,
  'totalBatches' : bigint,
  'passCount' : bigint,
  'avgQualityScore' : number,
  'openDeviations' : bigint,
  'failCount' : bigint,
}
export interface QualityOverview {
  'avgScore' : number,
  'total' : bigint,
  'highRisk' : bigint,
  'failed' : bigint,
  'passed' : bigint,
}
export interface RiskAuditEntry {
  'userName' : string,
  'userId' : string,
  'timestamp' : bigint,
  'riskLevel' : string,
  'creditsUsed' : bigint,
  'riskScore' : bigint,
  'systemName' : string,
}
export interface RiskBatch {
  'supplier' : string,
  'qualityScore' : number,
  'batchId' : string,
  'herbName' : string,
  'riskLevel' : string,
}
export interface ScoreTrend {
  'qualityScore' : number,
  'timestamp' : bigint,
  'batchId' : string,
}
export interface SupplierStats {
  'avgScore' : number,
  'passRate' : number,
  'supplier' : string,
  'totalBatches' : bigint,
}
export interface UserRecord {
  'id' : string,
  'status' : string,
  'institution' : string,
  'approvedAt' : [] | [bigint],
  'name' : string,
  'accessCode' : [] | [string],
  'codeGeneratedAt' : [] | [bigint],
  'email' : string,
  'registeredAt' : bigint,
  'purpose' : string,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE extends AyurNexis {}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];