/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface RiskBatch {
    supplier: string;
    qualityScore: number;
    batchId: string;
    herbName: string;
    riskLevel: string;
}
export interface QualityOverview {
    avgScore: number;
    total: bigint;
    highRisk: bigint;
    failed: bigint;
    passed: bigint;
}
export interface ScoreTrend {
    qualityScore: number;
    timestamp: bigint;
    batchId: string;
}
export interface RiskAuditEntry {
    userName: string;
    userId: string;
    timestamp: bigint;
    riskLevel: string;
    creditsUsed: bigint;
    riskScore: bigint;
    systemName: string;
}
export interface DashboardStats {
    passRate: number;
    totalBatches: bigint;
    passCount: bigint;
    avgQualityScore: number;
    openDeviations: bigint;
    failCount: bigint;
}
export interface http_header {
    value: string;
    name: string;
}
export interface UserRecord {
    id: string;
    status: string;
    institution: string;
    approvedAt?: bigint;
    name: string;
    accessCode?: string;
    codeGeneratedAt?: bigint;
    email: string;
    registeredAt: bigint;
    purpose: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface SupplierStats {
    avgScore: number;
    passRate: number;
    supplier: string;
    totalBatches: bigint;
}
export interface AyurNexisInterface {
    _transform(raw: {
        context: Uint8Array;
        response: http_request_result;
    }): Promise<http_request_result>;
    addAdmin(user: Principal): Promise<void>;
    adminApproveUser(userId: string, adminToken: string): Promise<boolean>;
    adminDeleteUser(userId: string, adminToken: string): Promise<boolean>;
    adminGenerateCode(userId: string, adminToken: string, expiryDays: bigint): Promise<string | null>;
    adminRevokeUser(userId: string, adminToken: string): Promise<boolean>;
    analyzeBatch(id: bigint): Promise<AnalysisResult | null>;
    callDeepSeek(prompt: string): Promise<string>;
    callDeepSeekExtended(prompt: string): Promise<string>;
    checkUserAccess(userId: string): Promise<string>;
    createBatch(input: BatchInput): Promise<bigint>;
    deductCredit(userId: string): Promise<boolean>;
    deleteBatch(id: bigint): Promise<boolean>;
    getAccessRequests(adminToken: string): Promise<Array<UserRecord>>;
    getAllAnalyses(): Promise<Array<AnalysisResult>>;
    getAllBatches(): Promise<Array<Batch>>;
    getAllUserCredits(adminToken: string): Promise<Array<[string, bigint]>>;
    getAnalysis(batchId: string): Promise<AnalysisResult | null>;
    getBatch(id: bigint): Promise<Batch | null>;
    getDashboardStats(): Promise<DashboardStats>;
    getDeviationReport(): Promise<Array<AnalysisResult>>;
    getMyAppRole(): Promise<AppRole | null>;
    getQualityOverview(): Promise<QualityOverview>;
    getRiskAssessment(): Promise<Array<RiskBatch>>;
    getRiskAuditLog(adminToken: string): Promise<Array<RiskAuditEntry>>;
    getScoreTrends(): Promise<Array<ScoreTrend>>;
    getSupplierStats(): Promise<Array<SupplierStats>>;
    getUserCodeExpiry(email: string): Promise<[bigint, bigint] | null>;
    getUserCredits(userId: string, adminToken: string): Promise<bigint>;
    getUserOwnCredits(userId: string): Promise<bigint>;
    getUserRecord(userId: string, adminToken: string): Promise<UserRecord | null>;
    isCallerAdmin(): Promise<boolean>;
    logRiskPrediction(userId: string, userName: string, systemName: string, riskScore: bigint, riskLevel: string): Promise<void>;
    removeAdmin(user: Principal): Promise<void>;
    seedDemoData(): Promise<void>;
    setAppRole(user: Principal, role: AppRole): Promise<void>;
    setUserCredits(userId: string, amount: bigint, adminToken: string): Promise<boolean>;
    submitAccessRequest(id: string, name: string, institution: string, email: string, purpose: string, registeredAt: bigint): Promise<boolean>;
    updateBatch(id: bigint, input: BatchInput): Promise<boolean>;
    verifyUserCode(email: string, code: string): Promise<string | null>;
}
export interface BatchInput {
    ash: number;
    region: string;
    supplier: string;
    heavyMetals: number;
    extractiveValue: number;
    dateReceived: string;
    notes: string;
    microbialCount: number;
    batchId: string;
    herbName: string;
    moisture: number;
}
export interface Batch {
    id: bigint;
    ash: number;
    region: string;
    supplier: string;
    createdBy: Principal;
    heavyMetals: number;
    extractiveValue: number;
    dateReceived: string;
    notes: string;
    microbialCount: number;
    batchId: string;
    herbName: string;
    moisture: number;
}
export interface AnalysisResult {
    region: string;
    status: string;
    probability: number;
    ashOk: boolean;
    supplier: string;
    extractiveOk: boolean;
    anomalyDetails: string;
    qualityScore: number;
    moistureOk: boolean;
    heavyMetalsOk: boolean;
    dateReceived: string;
    timestamp: bigint;
    microbialOk: boolean;
    batchId: string;
    herbName: string;
    anomaly: boolean;
}
export enum AppRole {
    admin = "admin",
    qaManager = "qaManager",
    labTechnician = "labTechnician"
}
export interface backendInterface extends AyurNexisInterface {
}
import type { AnalysisResult as _AnalysisResult, AppRole as _AppRole, Batch as _Batch, UserRecord as _UserRecord } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _transform(arg0: {
        context: Uint8Array;
        response: http_request_result;
    }): Promise<http_request_result> {
        if (this.processError) {
            try {
                const result = await this.actor._transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._transform(arg0);
            return result;
        }
    }
    async addAdmin(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAdmin(arg0);
            return result;
        }
    }
    async adminApproveUser(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminApproveUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminApproveUser(arg0, arg1);
            return result;
        }
    }
    async adminDeleteUser(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteUser(arg0, arg1);
            return result;
        }
    }
    async adminGenerateCode(arg0: string, arg1: string, arg2: bigint): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGenerateCode(arg0, arg1, arg2);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGenerateCode(arg0, arg1, arg2);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminRevokeUser(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminRevokeUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminRevokeUser(arg0, arg1);
            return result;
        }
    }
    async analyzeBatch(arg0: bigint): Promise<AnalysisResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.analyzeBatch(arg0);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.analyzeBatch(arg0);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async callDeepSeek(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.callDeepSeek(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.callDeepSeek(arg0);
            return result;
        }
    }
    async callDeepSeekExtended(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.callDeepSeekExtended(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.callDeepSeekExtended(arg0);
            return result;
        }
    }
    async checkUserAccess(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.checkUserAccess(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkUserAccess(arg0);
            return result;
        }
    }
    async createBatch(arg0: BatchInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createBatch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBatch(arg0);
            return result;
        }
    }
    async deductCredit(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deductCredit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deductCredit(arg0);
            return result;
        }
    }
    async deleteBatch(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBatch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBatch(arg0);
            return result;
        }
    }
    async getAccessRequests(arg0: string): Promise<Array<UserRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAccessRequests(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAccessRequests(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAnalyses(): Promise<Array<AnalysisResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAnalyses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAnalyses();
            return result;
        }
    }
    async getAllBatches(): Promise<Array<Batch>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBatches();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBatches();
            return result;
        }
    }
    async getAllUserCredits(arg0: string): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserCredits(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserCredits(arg0);
            return result;
        }
    }
    async getAnalysis(arg0: string): Promise<AnalysisResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalysis(arg0);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalysis(arg0);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBatch(arg0: bigint): Promise<Batch | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBatch(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBatch(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getDeviationReport(): Promise<Array<AnalysisResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDeviationReport();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDeviationReport();
            return result;
        }
    }
    async getMyAppRole(): Promise<AppRole | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyAppRole();
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyAppRole();
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQualityOverview(): Promise<QualityOverview> {
        if (this.processError) {
            try {
                const result = await this.actor.getQualityOverview();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQualityOverview();
            return result;
        }
    }
    async getRiskAssessment(): Promise<Array<RiskBatch>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRiskAssessment();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRiskAssessment();
            return result;
        }
    }
    async getRiskAuditLog(arg0: string): Promise<Array<RiskAuditEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRiskAuditLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRiskAuditLog(arg0);
            return result;
        }
    }
    async getScoreTrends(): Promise<Array<ScoreTrend>> {
        if (this.processError) {
            try {
                const result = await this.actor.getScoreTrends();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScoreTrends();
            return result;
        }
    }
    async getSupplierStats(): Promise<Array<SupplierStats>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSupplierStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSupplierStats();
            return result;
        }
    }
    async getUserCodeExpiry(arg0: string): Promise<[bigint, bigint] | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserCodeExpiry(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserCodeExpiry(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserCredits(arg0: string, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserCredits(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserCredits(arg0, arg1);
            return result;
        }
    }
    async getUserOwnCredits(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserOwnCredits(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserOwnCredits(arg0);
            return result;
        }
    }
    async getUserRecord(arg0: string, arg1: string): Promise<UserRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserRecord(arg0, arg1);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserRecord(arg0, arg1);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async logRiskPrediction(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logRiskPrediction(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logRiskPrediction(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async removeAdmin(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeAdmin(arg0);
            return result;
        }
    }
    async seedDemoData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedDemoData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedDemoData();
            return result;
        }
    }
    async setAppRole(arg0: Principal, arg1: AppRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAppRole(arg0, to_candid_AppRole_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAppRole(arg0, to_candid_AppRole_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setUserCredits(arg0: string, arg1: bigint, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserCredits(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserCredits(arg0, arg1, arg2);
            return result;
        }
    }
    async submitAccessRequest(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.submitAccessRequest(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitAccessRequest(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateBatch(arg0: bigint, arg1: BatchInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBatch(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBatch(arg0, arg1);
            return result;
        }
    }
    async verifyUserCode(arg0: string, arg1: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyUserCode(arg0, arg1);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyUserCode(arg0, arg1);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AppRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppRole): AppRole {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_UserRecord_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRecord): UserRecord {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [[bigint, bigint]]): [bigint, bigint] | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserRecord]): UserRecord | null {
    return value.length === 0 ? null : from_candid_UserRecord_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AnalysisResult]): AnalysisResult | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Batch]): Batch | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AppRole]): AppRole | null {
    return value.length === 0 ? null : from_candid_AppRole_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    institution: string;
    approvedAt: [] | [bigint];
    name: string;
    accessCode: [] | [string];
    codeGeneratedAt: [] | [bigint];
    email: string;
    registeredAt: bigint;
    purpose: string;
}): {
    id: string;
    status: string;
    institution: string;
    approvedAt?: bigint;
    name: string;
    accessCode?: string;
    codeGeneratedAt?: bigint;
    email: string;
    registeredAt: bigint;
    purpose: string;
} {
    return {
        id: value.id,
        status: value.status,
        institution: value.institution,
        approvedAt: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.approvedAt)),
        name: value.name,
        accessCode: record_opt_to_undefined(from_candid_opt_n1(_uploadFile, _downloadFile, value.accessCode)),
        codeGeneratedAt: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.codeGeneratedAt)),
        email: value.email,
        registeredAt: value.registeredAt,
        purpose: value.purpose
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    qaManager: null;
} | {
    labTechnician: null;
}): AppRole {
    return "admin" in value ? AppRole.admin : "qaManager" in value ? AppRole.qaManager : "labTechnician" in value ? AppRole.labTechnician : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserRecord>): Array<UserRecord> {
    return value.map((x)=>from_candid_UserRecord_n4(_uploadFile, _downloadFile, x));
}
function to_candid_AppRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppRole): _AppRole {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppRole): {
    admin: null;
} | {
    qaManager: null;
} | {
    labTechnician: null;
} {
    return value == AppRole.admin ? {
        admin: null
    } : value == AppRole.qaManager ? {
        qaManager: null
    } : value == AppRole.labTechnician ? {
        labTechnician: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
